name: Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches:
    - master

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.10']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.1.4
        with:
          poetry-version: 1.1.12
      - name: install
        run: poetry install
      - name: flake8
        run: poetry run flake8 .
      - name: mypy
        run: poetry run mypy .
      - name: black
        run: poetry run black --check .
      - name: test
        run: poetry run pytest -v tests/
